version: "3.8"

services:

  cozy:
    image: dracco-lofi:cozy
    env_file:
      - .env.cozy
    volumes:
      - ./musicas_cozy:/app/musicas_cozy:ro
      - ./video:/app/video:ro
      - ./config:/app/config:ro
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 1500M
        reservations:
          cpus: '0.8'
          memory: 1200M
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      health_check:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/"]
        interval: 10s
        timeout: 3s
        retries: 3
        start_period: 20s

  dracco:
    image: dracco-lofi:dracco
    env_file:
      - .env.dracco
    volumes:
      - ./musicas_dracco:/app/musicas_dracco:ro
      - ./video:/app/video:ro
      - ./config:/app/config:ro
    ports:
      - target: 8080
        published: 8082
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 1500M
        reservations:
          cpus: '0.8'
          memory: 1200M
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      health_check:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/"]
        interval: 10s
        timeout: 3s
        retries: 3
        start_period: 20s
