version: "3.8"

services:

  cozy:
    image: melodanilo/dracco-lofi:latest
    env_file:
      - .env.cozy
    volumes:
      - type: bind
        source: ./musicas_cozy
        target: /app/musicas_cozy
        read_only: true
      - type: bind
        source: ./video
        target: /app/video
        read_only: true
      - type: bind
        source: ./config
        target: /app/config
        read_only: true
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - live_net

  dracco:
    image: melodanilo/dracco-lofi:latest
    env_file:
      - .env.dracco
    volumes:
      - type: bind
        source: ./musicas_dracco
        target: /app/musicas_dracco
        read_only: true
      - type: bind
        source: ./video
        target: /app/video
        read_only: true
      - type: bind
        source: ./config
        target: /app/config
        read_only: true
    ports:
      - target: 8080
        published: 8082
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - live_net

networks:
  live_net:
    driver: overlay
