version: "3.8"

services:
  dashboard:
    image: melodanilo/dracco-lofi:latest
    command: python3 /app/dashboard.py
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: start-first
    environment:
      DASHBOARD_USER: ${DASHBOARD_USER:-admin}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD:-admin123}
      DASHBOARD_SECRET_KEY: ${DASHBOARD_SECRET_KEY:-change-me-in-production}
    volumes:
      - ./config:/app/config:rw
      - ./video:/app/video:ro
      - ./logs:/app/logs:rw
      - ./control:/app/control:rw
      - ./stats:/app/stats:rw
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/login"]
      interval: 10s
      timeout: 2s
      retries: 5

  cozy:
    image: melodanilo/dracco-lofi:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: start-first
    environment:
      CHANNEL_NAME: "cozy"
    volumes:
      - ./config:/app/config:rw
      - ./musicas_cozy:/app/musicas:ro
      - ./video:/app/video:ro
      - ./logs:/app/logs:rw
      - ./control:/app/control:rw
      - ./stats:/app/stats:rw
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 2s
      retries: 5

  dracco:
    image: melodanilo/dracco-lofi:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: start-first
    environment:
      CHANNEL_NAME: "dracco"
    volumes:
      - ./config:/app/config:rw
      - ./musicas_dracco:/app/musicas:ro
      - ./video:/app/video:ro
      - ./logs:/app/logs:rw
      - ./control:/app/control:rw
      - ./stats:/app/stats:rw
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 2s
      retries: 5
